### ISSUE TITLE
Не запускаются тесты

### ISSUE THREAD

**Issue by DeminaDaria** [DeminaDaria/HW_10_ManagerMovie#3]
Не получается запустить тесты, хотя в самом начале работы тесты работали и по покрытию было 100%.
Тесты не запускаются во всём проекте.
В других проектах тесты работают.

### Результат ответа 
```
окт. 25, 2020 7:09:16 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-jupiter' failed to discover tests
java.lang.NoSuchMethodError: 'org.junit.platform.engine.EngineDiscoveryListener org.junit.platform.engine.EngineDiscoveryRequest.getDiscoveryListener()'
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:88)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:82)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:45)
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:177)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:164)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)


Process finished with exit code 0
```

### Шаги по воспроизведению (Steps to reproduce)

1. Открыть в IntelliJ IDEA проект:

https://github.com/DeminaDaria/HW_10_ManagerMovie.git

https://github.com/DeminaDaria/HW_10_ManagerMovie/pull/2

2. Запустить mvn verify -e.
 
### Ожидаемый результат (Expected result)

Все тесты проходят, верификация проходит.

### Фактический результат (Actual result)

Тесты не запускаются.

### Программное окружение
 * Устройство: Windows 10 Home 64bit, [Version 10.0.19041.450]
 * java: 11.0.8 2020-07-14
* IntelliJ IDEA Community 2020.2
 
 ### Скриншоты

![HW-10 – MovieRepositoryTest](https://user-images.githubusercontent.com/61200143/97112690-cb174d80-16f6-11eb-803e-a5661c63933a.png)

![HW-10 – MovieRepositoryTest java  cart  2020-10-25](https://user-images.githubusercontent.com/61200143/97112729-f26e1a80-16f6-11eb-8c25-979061076721.png)

![MojoExecutionException - Apache Maven - Apache Sof](https://user-images.githubusercontent.com/61200143/97112732-f7cb6500-16f6-11eb-86bd-d2a1d94738af.png)

![Layers by DeminaDaria · Pull Request #2 · DeminaDa](https://user-images.githubusercontent.com/61200143/97112760-25181300-16f7-11eb-96fa-b62df2f5b8df.png)

**Comment by DeminaDaria** [comment]
В pom.xml в в секции dependencies давайте перенесём зависимость для mockito-junit-jupiter после junit-jupiter и тесты перестанут падать.
